# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#'
MARSc <- function(X, stoptol, Lambdapath, stopmethod, maxiter, printyes, printyessub, sigma, numlam, maxlambdacheck) {
    .Call(`_MARS_MARSc`, X, stoptol, Lambdapath, stopmethod, maxiter, printyes, printyessub, sigma, numlam, maxlambdacheck)
}

#' @export
#'
PMEASc <- function(X, stoptol, Lambdapath, calmethod, stopmethod, maxiter, printyes, printyessub, sigma, numlam, maxlambdacheck) {
    .Call(`_MARS_PMEASc`, X, stoptol, Lambdapath, calmethod, stopmethod, maxiter, printyes, printyessub, sigma, numlam, maxlambdacheck)
}

partgradient <- function(Zin, lambda) {
    .Call(`_MARS_partgradient`, Zin, lambda)
}

